---
title: "Tarea13_AlejandroBarrantes"
author: "Alejandro Barrantes Castro"
date: "2023-06-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(snow)
library(traineR)
library(caret)
library(rpart.plot)
library(ggplot2)
library(dplyr)
library(glue)
library(tidyverse)
library(scales)
library(class)
library(e1071)
library(randomForest)
```

# Funciones generales

```{r}
plotROC <- function(prediccion, real, adicionar = FALSE, color = "red") {
  pred <- ROCR::prediction(prediccion, real)    
  perf <- ROCR::performance(pred, "tpr", "fpr")
  plot(perf, col = color, add = adicionar, main = "Curva ROC")
  segments(0, 0, 1, 1, col='black')
  grid()  
}

calculaAreaROC <- function(prediccion, real) {
  pred <- ROCR::prediction(prediccion, real)
  perf <- ROCR::performance(pred, "auc")
  auc <- as.numeric(perf@y.values)
  return(auc)
}

```


# Ejercicio #1

# Lectura

```{r}
setwd("~/ALEJANDRO/1er Ciclo 2023/Mineria de Datos/Tarea 7/Datos Clase y Tareas")
Datos <- read.csv("Tumores.csv", header=TRUE, sep=',',dec='.',stringsAsFactors = T)
enteros <- sapply(Datos, is.integer)
Datos[enteros] <- lapply(Datos[enteros], as.factor)

Datos$tipo <- factor(Datos$tipo)
Datos <- subset(Datos, select = -1)

set.seed(123) # Fijamos la semilla para reproducibilidad
indice <- createDataPartition(y = Datos$tipo, p = 0.25, list = FALSE)
ttesting <- Datos[indice, ]
ttraining <- Datos[-indice, ]
```



## 1.1

```{r}

#====================================
#svm
modelo <- train.svm(tipo ~ ., data = ttraining)
prediccion <- predict(modelo, ttesting, type = "prob")

Score <- prediccion$prediction[,2]
Clase <- ttesting$tipo
# Genera el gráfico
plotROC(Score,Clase)

svm_area <- calculaAreaROC(Score, Clase)



#====================================
#knn
modelo <- train.knn(tipo ~ ., data = ttraining, kmax = tam)
prediccion <- predict(modelo, ttesting, type = "prob")


Score <- prediccion$prediction[,2]
Clase <- ttesting$tipo
# Genera el gráfico
plotROC(Score,Clase, adicionar=TRUE, color = "blue")

knn_area <- calculaAreaROC(Score, Clase)

#====================================
#arboles
modelo <- train.rpart(tipo ~ ., data = ttraining)
prediccion <- predict(modelo, ttesting, type = "prob")


Score <- prediccion$prediction[,2]
Clase <- ttesting$tipo
# Genera el gráfico
plotROC(Score,Clase, adicionar=TRUE, color = "green")

rpart_area <- calculaAreaROC(Score, Clase)

#====================================
#bosques
modelo <- train.randomForest(tipo ~ ., data = ttraining)
prediccion <- predict(modelo, ttesting, type = "prob")


Score <- prediccion$prediction[,2]
Clase <- ttesting$tipo
# Genera el gráfico
plotROC(Score,Clase, adicionar=TRUE, color = "yellow")

randomForest_area <- calculaAreaROC(Score, Clase)

#====================================
#potenciacion
modelo <- train.ada(tipo ~ ., data = ttraining)
prediccion <- predict(modelo, ttesting, type = "prob")


Score <- prediccion$prediction[,2]
Clase <- ttesting$tipo
# Genera el gráfico
plotROC(Score,Clase, adicionar=TRUE, color = "orange")

ada_area <- calculaAreaROC(Score, Clase)

# #====================================
# #xgboost
# modelo <- train.xgboost(tipo ~ ., data = ttraining, nrounds = 500)
# prediccion <- predict(modelo, ttesting, type = "prob")
# 
# 
# Score <- prediccion$prediction[,2]
# Clase <- ttesting$tipo
# # Genera el gráfico
# plotROC(Score,Clase, adicionar=TRUE, color = "lightblue")
xgboost_area <- calculaAreaROC(Score, Clase)

#====================================
#lda
modelo <- train.lda(tipo ~ ., data = ttraining)
prediccion <- predict(modelo, ttesting, type = "prob")


Score <- prediccion$prediction[,2]
Clase <- ttesting$tipo
# Genera el gráfico
plotROC(Score,Clase, adicionar=TRUE, color = "lightgray")

lda_area <- calculaAreaROC(Score, Clase)

#====================================
#bayes
modelo <- train.bayes(tipo ~ ., data = ttraining)
prediccion <- predict(modelo, ttesting, type = "prob")


Score <- prediccion$prediction[,2]
Clase <- ttesting$tipo
# Genera el gráfico
plotROC(Score,Clase, adicionar=TRUE, color = "brown")

bayes_area <- calculaAreaROC(Score, Clase)


#====================================
#nnet
modelo <- train.nnet(tipo ~ ., data = ttraining, size = 4, maxit = 1000, MaxNWts = 400, trace = FALSE)
prediccion <- predict(modelo, ttesting, type = "prob")


Score <- prediccion$prediction[,2]
Clase <- ttesting$tipo
# Genera el gráfico
plotROC(Score,Clase, adicionar=TRUE, color = "purple")

nnet_area <- calculaAreaROC(Score, Clase)


```


# El mejor hasta el momento parecen ser mejores bosques, el cual es la curva que esta en color amarillo o ADA, la cual esta en color anaranjado, esta es muy parecida a la curva de bosques, por lo cual cuesta observarla bien, sin embargo se encuentra en algunos momentos por encima de bosques.

# 1.2
```{r}

resultados <- data.frame(Modelo = c("SVM", "KNN", "RPART", "RFOREST","ADA", "XGBOOST",
                                    "LDA","BAYES", "NNET"),
                         AREA = c(svm_area, knn_area,rpart_area, randomForest_area,
                                     ada_area,xgboost_area,lda_area,bayes_area,nnet_area))

mejor_modelo <- resultados[which.max(resultados$AREA), "Modelo"]

mejor_modelo

randomForest_area
```













